"""目标配置准备、路径解析与稳定渲染。"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any, Mapping

import tomlkit

from .errors import ConfigError
from .matcher import matched_overlays
from .merger import merge_target
from .variables import resolve_variables, substitute_tree


def prepare_target(
    declaration: dict[str, Any],
    target_name: str,
    context: dict[str, Any],
    environ: Mapping[str, str] | None = None,
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    target = declaration.get("targets", {}).get(target_name)
    if target is None:
        raise ConfigError("CONFIG_SCHEMA_INVALID", f"声明中不存在目标：{target_name}", location=f"targets.{target_name}")

    overlays = matched_overlays(target.get("overlays", []), context)
    definitions = dict(declaration.get("variables") or {})
    for overlay in overlays:
        definitions.update(overlay.get("variables") or {})
    variables = resolve_variables(definitions, context, environ)
    merged = merge_target(target.get("base", {}), overlays)
    return substitute_tree(merged, variables, location=f"targets.{target_name}", environ=environ), overlays


def render_codex(data: dict[str, Any]) -> str:
    try:
        body = tomlkit.dumps(data).rstrip("\n")
        content = "# Generated by agent-config-sync.\n# Do not edit directly.\n\n" + body + "\n"
        tomlkit.parse(content)
        return content
    except Exception as exc:
        raise ConfigError("CODEX_TOML_INVALID", f"无法生成合法 TOML：{exc}") from exc


def render_claude(data: dict[str, Any]) -> str:
    try:
        content = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
        json.loads(content)
        return content
    except (TypeError, ValueError) as exc:
        raise ConfigError("CLAUDE_JSON_INVALID", f"无法生成合法 JSON：{exc}") from exc


def render_target(target_name: str, data: dict[str, Any]) -> str:
    if target_name == "codex":
        return render_codex(data)
    if target_name == "claude":
        return render_claude(data)
    raise ConfigError("CONFIG_SCHEMA_INVALID", f"未知目标：{target_name}")


def resolve_output_path(output: str, context: Mapping[str, Any], environ: Mapping[str, str] | None = None) -> Path:
    variables = resolve_variables({}, context, environ)
    expanded = substitute_tree(output, variables, location="output", environ=environ)
    if expanded == "~":
        expanded = str(context["home"])
    elif expanded.startswith("~/") or expanded.startswith("~\\"):
        expanded = str(Path(str(context["home"])) / expanded[2:])
    expanded = os.path.expandvars(expanded)
    return Path(expanded).resolve()


def output_path_for(declaration: dict[str, Any], target_name: str, context: Mapping[str, Any]) -> Path:
    target = declaration["targets"][target_name]
    return resolve_output_path(target["output"], context)
